name: ugd_timer
description: Timer simple untuk UGD di lab
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.0
  font_awesome_flutter: ^10.5.0
  animated_flip_counter: ^0.2.6
  flutter_animate: ^4.2.0+1
  window_manager: ^0.3.6
  override_text_scale_factor: ^1.0.2
  url_launcher: ^6.1.14
  pausable_timer: ^2.0.0+1
  keymap: ^0.0.92
  flutter_styled_toast: ^2.2.1
  audioplayers: ^5.2.0
  file_picker: ^5.5.0
  google_fonts: ^6.1.0
  fullscreen: ^1.0.3
  lottie: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner:

flutter:
  uses-material-design: true

  assets:
    - assets/lottie_pattern_bg.json
