name: ugd_timer
description: "A simple and beautiful timer for programming and timing coding practice"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  bitsdojo_window: ^0.1.6
  fluent_ui: ^4.8.5
  flutter:
    sdk: flutter
  flutter_acrylic: ^1.1.3
  flutter_hooks: ^0.20.4
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  freezed: ^2.4.6
  gap: ^3.0.1
  hooks_riverpod: ^2.4.9
  hotkey_manager: ^0.2.1
  intl: any
  responsive_sizer: ^3.3.0+1
  riverpod: ^2.4.9
  window_manager: ^0.3.7
  freezed_annotation: ^2.4.1
  json_serializable: ^6.7.1
  riverpod_annotation: ^2.3.3
  logger: ^2.0.2+1
  google_fonts: ^6.1.0
  animated_flip_counter: ^0.2.6
  shadow: ^1.5.0
  font_awesome_flutter: ^10.6.0
  lottie: ^3.0.0
  css_filter: ^1.0.3
  flutter_markdown: ^0.6.18+3
  url_launcher: ^6.2.4
  simple_animations: ^5.0.2
  shared_preferences: ^2.2.2
  json_annotation: ^4.8.1
  archive: ^3.4.10
  path_provider: ^2.1.2
  file_picker: ^8.0.0+1

dev_dependencies:
  build_runner: ^2.4.8
  custom_lint: ^0.5.8
  dependency_validator: ^3.2.3
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  test: ^1.24.9
  isar_generator: ^3.1.0+1
  riverpod_lint: ^2.1.1
  very_good_analysis: ^5.1.0
  riverpod_generator: ^2.3.3

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/lottie/